name: Reformat Java Code

on: [push]  # Trigger on push events

jobs:
  reformat:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4  # Checkout code

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Install Checkstyle
        run: mvn --batch-mode org.apache.maven.plugins:maven-checkstyle-plugin:checkstyle

      - name: Checkstyle
        run: mvn checkstyle:check -Dcheckstyle.config.location=../linters/sun_checks.xml
