---
name: Find Style and Format Violations

on:
  push: null
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

env:
  APPLY_FIXES: all
  APPLY_FIXES_EVENT: push
  APPLY_FIXES_MODE: commit
  content: "demo content"

jobs:
  mega-linter:
    name: Find Violations Using Mega Linter
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: read
      issues: write
      pull-requests: write
      # To report GitHub Actions status checks
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Mega-Linter
        id: ml
        uses: oxsecurity/megalinter/flavors/java@beta
        env:
          VALIDATE_ALL_CODEBASE: true # ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }} # Validates all source when push on master, else just the git diff with master. Override with true if you always want to lint all sources
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ENABLE: JAVA
          ENABLE_LINTERS: JAVA_CHECKSTYLE
          DISABLE_LINTERS: JAVA_PMD
          JAVA_CHECKSTYLE_CONFIG_FILE: sun_checks.xml
          APPLY_FIXES: JAVA_CHECKSTYLE
          APPLY_FIXES_EVENT: push
          APPLY_FIXES_MODE: commit

      - name: Extract lines
        if: success() || failure()
        run: |
              grep "/github/workspace/" megalinter-reports/megalinter.log
              grep "/github/workspace/" megalinter-reports/megalinter.log > extracted-lines.txt

      - name: Read content from artifact
        id: read-log
        if: success() || failure()
        run: |
          error_lines=$(grep "/github/workspace/" megalinter-reports/megalinter.log)
          echo "error-lines: $error_lines"
          paragraph=$(echo "$error_lines" | tr '\n' ' ')
          echo "::set-output name=content::$error_lines"
          echo "paragraph - $paragraph"

      - name: Debug
        if: always()
        run: |
          echo "error lines: $error_lines"
          echo "paragraph: $paragraph"

      - uses: mshick/add-pr-comment@v2
        if: always()
        with:
          message-path: |
            extracted-lines.txt
          find: |
            Rules config: [/github/workspace/.github/linters/sun_checks.xml]
            [ERROR] - Rules config: [/github/workspace/.github/linters/sun_checks.xml]
            /github/workspace/src/main/java/
          replace: |
            -
            -
            -
          allow-repeats: false
