---
name: Find Style and Format Violations

on:
  push: null
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build:
    name: Find Violations
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0

      - name: Load super-linter configuration
        run: cat .github/super-linter.env >> "$GITHUB_ENV"

      - name: Super Linter checks for violations
        uses: super-linter/super-linter@v5.7.2 # x-release-please-version
        continue-on-error: true
        env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JAVA_FILE_NAME: google_checks.xml
          VALIDATE_JAVA: true
          #          ACTIONS_RUNNER_DEBUG: true
          DEFAULT_BRANCH: main
          # To report GitHub Actions status checks
          #          LINTER_RULES_PATH: config/lint
          FILTER_REGEX_INCLUDE: "^(.*src/.*|.*test/.*)"

      - name: Save Super Linter Report
        uses: actions/upload-artifact@v4
        with:
          name: super-linter-report
          path: super-linter-report.json
          if-no-files-found: error

  save-report:
    name: lint code and save report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0

      - name: Load super-linter configuration
        run: cat .github/super-linter.env >> "$GITHUB_ENV"


      - name: run super linter
        run: docker run -v .:/tmp/lint --rm ghcr.io/super-linter/super-linter:latest
        env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: save report log
        run: echo "${{ steps.lint.outputs.stdout }}" > linter_report.log

      - name: Save report to artifact
        uses: actions/upload-artifact@v4
        with:
          name: linter-report
          path: linter-report.log


#  get_report:
#    name: Get Super Linter report
#    runs-on: ubuntu-latest
#    needs: build
#
#    permissions:
#      contents: read
#      packages: read
#      # To report GitHub Actions status checks
#      statuses: write
#
#    steps:
#      - name: Download Linter Report
#        uses: actions/download-artifact@v4
#        with:
#          name: super-linter-report
#          path: ./linter-reports/super-linter-report.json
#
#      - name: Display Linter Report
#        uses: softprops/action-gh-release@v1
#        with:
#          tag_name: 123
#          files: ./linter-reports/super-linter-report.json
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}