---
name: Find Style and Format Violations

on:
  push: null
  pull_request:
    branches: [master, main]
  workflow_dispatch:

jobs:
  build:
    name: Find Violations
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0

      - name: Super Linter checks for violations
        uses: super-linter/super-linter@v5.7.2  # x-release-please-version
        continue-on-error: true
        env:
#          ACTIONS_RUNNER_DEBUG: true
          VALIDATE_JAVA: true
          DEFAULT_BRANCH: main
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          LINTER_RULES_PATH: config/lint
          JAVA_FILE_NAME: google_checks.xml
          FILTER_REGEX_INCLUDE: "^(.*src/.*|.*test/.*)"
#          VALIDATE_ALL_CODEBASE: false # Only lint changed files
          DISABLE_ERRORS: false  # Treat errors as failures
          DISABLE_WARNINGS: false  # Treat warnings as failures

      - name: Save Super Linter Report
        uses: actions/upload-artifact@v3
        with:
          name: super-linter-report
          path: ./linter-reports/super-linter-report.json

  get_report:
    name: Get Super Linter report
    runs-on: ubuntu-latest
    needs: build

    permissions:
      contents: write
      packages: write
      # To report GitHub Actions status checks
      statuses: write

    steps:
      - name: Download Linter Report
        uses: actions/download-artifact@v2
        with:
          name: super-linter-report
          path: ./linter-reports/super-linter-report.json

      - name: Display Linter Report
        uses: softprops/action-gh-release@v1
        with:
          tag_name: 123
          files: ./linter-reports/super-linter-report.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}