name: Format Java Code

on:
  push: null
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  format-code:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - uses: pmd/pmd-github-action@v1
        id: pmd
        with:
          version: '6.40.0'
          sourcePath: 'src/main/java'
          rulesets: '.github/linters/sum_checks.xml'

      - name: Fail build if there are violations
        if: steps.pmd.outputs.violations != 0
        run: exit 1

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: pmd-report.sarif